services:
  exporter-tests:
    image: golang:1.26-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: go test -v ./...
    environment:
      - LISTEN_ADDRESS=${LISTEN_ADDRESS:-:8080}
      - METRICS_PATH=${METRICS_PATH:-/metrics}
      - XUI_BASE_URL=${XUI_BASE_URL:-http://localhost:5353}
      - XUI_SECRET_PATH=${XUI_SECRET_PATH:-/}
      - XUI_ACCESS_TOKEN=${XUI_ACCESS_TOKEN:-abcd}
      # TODO: Is useless for now, but we can use it to debug the exporter in the future
      - LOG_LEVEL=debug
